apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: forecast-of-response
spec:
  environments:
    - name: test
      build:
        from: deploy-to-radix
  components:
    - name: web
      image: mariner.azurecr.io/for/web:latest
      alwaysPullImageOnDeploy: true
      ports:
        - name: http
          port: 3000

    - name: api
      image: mariner.azurecr.io/for/api:latest
      alwaysPullImageOnDeploy: true
      environmentConfig:
        - environment: test
          variables:
            DMSS_HOST: dmss
            DMSS_PORT: 5000
            ENVIRONMENT: production
      ports:
        - name: flask
          port: 5000
      publicPort: flask

    - name: dmss
      image: mariner.azurecr.io/dmt/dmss:latest
      alwaysPullImageOnDeploy: true
      secrets:
        - MONGO_AZURE_URI
        - SECRET_KEY
        - MONGO_INITDB_ROOT_USERNAME
        - MONGO_INITDB_ROOT_PASSWORD
      environmentConfig:
        - environment: test
          variables:
            AUTH_ENABLED: "True"
            ENVIRONMENT: production
            OAUTH_WELL_KNOWN: https://login.microsoftonline.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/v2.0/.well-known/openid-configuration
            OAUTH_CLIENT_ID: 97a6b5bd-63fb-42c6-bb75-7e5de2394ba0
      ports:
        - name: rest
          port: 5000
      publicPort: rest

    - name: proxy
      image: mariner.azurecr.io/dmt/nginx:latest
      ports:
        - name: nginx
          port: 80
      publicPort: nginx

  dnsAppAlias:
    environment: test
    component: proxy

  privateImageHubs:
    mariner.azurecr.io:
      username: mariner
      email: stoo@equinor.com
