apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: forecast-of-response
spec:
  environments:
    - name: test
      build:
        from: master
    - name: prod
      build:
        from: master
  components:
    - name: web
      image: mariner.azurecr.io/for/web:{imageTagName}
      environmentConfig:
        - environment: test
          imageTagName: latest
        - environment: prod
          imageTagName: production
      alwaysPullImageOnDeploy: true
      ports:
        - name: http
          port: 3000

    - name: api
      image: mariner.azurecr.io/for/api:{imageTagName}
      alwaysPullImageOnDeploy: true
      secrets:
        - AZURE_SP_SECRET
        - SCHEDULER_REDIS_PASSWORD
        - SIMA_LICENSE
      variables:
        JOB_SERVICE_ENABLED: 1
        SCHEDULER_REDIS_PORT: 6380
        SCHEDULER_REDIS_SSL: "true"
        DMSS_API: http://dmss:5000
        ENVIRONMENT: production
        SCHEDULER_ENVS_TO_EXPORT: "PUBLIC_DMSS_API,SIMA_LICENSE"
        AZURE_JOB_SUBSCRIPTION: 93b83577-619d-4fb9-bfdf-f7a07d24cfbe
        AZURE_JOB_RESOURCE_GROUP: S059-Forecast-of-response
        AZURE_JOB_TENANT_ID: 3aa4a235-b6e2-48d5-9195-7fcf05b459b0
        AZURE_JOB_CLIENT_ID: ee7dbf49-e358-4c9c-a7e4-fb6d56c02205
      environmentConfig:
        - environment: test
          imageTagName: latest
          variables:
            SCHEDULER_REDIS_HOST: dmt-scheduler.redis.cache.windows.net
            PUBLIC_DMSS_API: https://dmss-forecast-of-response-test.radix.equinor.com
        - environment: prod
          imageTagName: production
          variables:
            SCHEDULER_REDIS_HOST: dmt-scheduler-prod.redis.cache.windows.net
            PUBLIC_DMSS_API: https://dmss-forecast-of-response-prod.radix.equinor.com
      ports:
        - name: flask
          port: 5000
      publicPort: flask

    - name: dmss
      image: mariner.azurecr.io/dmss:latest
      alwaysPullImageOnDeploy: true
      secrets:
        - MONGO_AZURE_URI
        - SECRET_KEY
      variables:
        LOGGING_LEVEL: "debug"
        AUTH_ENABLED: "True"
        ENVIRONMENT: production
        OAUTH_WELL_KNOWN: https://login.microsoftonline.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/v2.0/.well-known/openid-configuration
        OAUTH_TOKEN_ENDPOINT: https://login.microsoftonline.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/oauth2/v2.0/token
        OAUTH_AUTH_ENDPOINT: https://login.microsoftonline.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/oauth2/v2.0/authorize
        OAUTH_CLIENT_ID: ee7dbf49-e358-4c9c-a7e4-fb6d56c02205
        OAUTH_AUDIENCE: ee7dbf49-e358-4c9c-a7e4-fb6d56c02205
      ports:
        - name: rest
          port: 5000
      publicPort: rest


    - name: proxy
      image: mariner.azurecr.io/dmt/nginx:latest
      ports:
        - name: nginx
          port: 8080
      publicPort: nginx

  dnsAppAlias:
    environment: prod
    component: proxy

  privateImageHubs:
    mariner.azurecr.io:
      username: mariner
      email: stoo@equinor.com
