apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: forecast-of-response
spec:
  environments:
    - name: test
      build:
        from: master
  components:
    - name: web
      image: mariner.azurecr.io/for/web:latest
      alwaysPullImageOnDeploy: true
      ports:
        - name: http
          port: 3000

    - name: api
      image: mariner.azurecr.io/for/api:latest
      alwaysPullImageOnDeploy: true
      secrets:
        - AZURE_SP_SECRET
        - SCHEDULER_REDIS_PASSWORD
      environmentConfig:
        - environment: test
          variables:
            SCHEDULER_REDIS_HOST: dmt-scheduler.redis.cache.windows.net
            SCHEDULER_REDIS_PORT: 6380
            SCHEDULER_REDIS_SSL: "true"
            AZURE_JOB_SUBSCRIPTION: 1d249b90-3592-49bd-b14e-446340a5cf6b
            AZURE_JOB_RESOURCE_GROUP: MSARGDev
            AZURE_JOB_SP_TENANT_ID: 3aa4a235-b6e2-48d5-9195-7fcf05b459b0
            AZURE_JOB_SP_CLIENT_ID: 97a6b5bd-63fb-42c6-bb75-7e5de2394ba0
            DMSS_API: http://dmss:5000
            ENVIRONMENT: production
      ports:
        - name: flask
          port: 5000
      publicPort: flask

    - name: dmss
      image: mariner.azurecr.io/dmss:latest
      alwaysPullImageOnDeploy: true
      secrets:
        - MONGO_AZURE_URI
        - SECRET_KEY
      environmentConfig:
        - environment: test
          variables:
            AUTH_ENABLED: "True"
            ENVIRONMENT: production
            OAUTH_WELL_KNOWN: https://login.microsoftonline.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/v2.0/.well-known/openid-configuration
            OAUTH_TOKEN_ENDPOINT: https://login.microsoftonline.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/oauth2/v2.0/token
            OAUTH_AUTH_ENDPOINT: https://login.microsoftonline.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/oauth2/v2.0/authorize
            OAUTH_CLIENT_ID: ee7dbf49-e358-4c9c-a7e4-fb6d56c02205
            OAUTH_AUDIENCE: ee7dbf49-e358-4c9c-a7e4-fb6d56c02205
      ports:
        - name: rest
          port: 5000
      publicPort: rest

    - name: proxy
      image: mariner.azurecr.io/dmt/nginx:latest
      ports:
        - name: nginx
          port: 8080
      publicPort: nginx

  dnsAppAlias:
    environment: test
    component: proxy

  privateImageHubs:
    mariner.azurecr.io:
      username: mariner
      email: stoo@equinor.com
